version: '3'
services:
  alice:
    image: bsc_validator:latest
    environment:
     - AUTHORITY_NAME=alice
    volumes:
      - type: bind
        source: ./keys/password.txt
        target: /data/keys/password.txt
      - ./keys/alice:/data/keys/alice
  bob:
    image: bsc_validator:latest
    environment:
     - AUTHORITY_NAME=bob
    volumes:
      - type: bind
        source: ./keys/password.txt
        target: /data/keys/password.txt
      - ./keys/bob:/data/keys/bob
  charlie:
    image: bsc_validator:latest
    environment:
     - AUTHORITY_NAME=charlie
    volumes:
      - type: bind
        source: ./keys/password.txt
        target: /data/keys/password.txt
      - ./keys/charlie:/data/keys/charlie
  dave:
    image: bsc_validator:latest
    environment:
     - AUTHORITY_NAME=dave
    volumes:
      - type: bind
        source: ./keys/password.txt
        target: /data/keys/password.txt
      - ./keys/dave:/data/keys/dave
  eve:
    image: bsc_validator:latest
    environment:
     - AUTHORITY_NAME=eve
    volumes:
      - type: bind
        source: ./keys/password.txt
        target: /data/keys/password.txt
      - ./keys/eve:/data/keys/eve