version: '3'
services:
  alice:
    image: bsc_validator:latest
    environment:
     - AUTHORITY_NAME=alice
    volumes:
      - ./keys/alice:/data/keys
      - ./keys/password.txt:/data/keys/password.txt
  bob:
    image: bsc_validator:latest
    environment:
     - AUTHORITY_NAME=bob
    volumes:
      - ./keys/bob:/data/keys
      - ./keys/password.txt:/data/keys/password.txt
  charlie:
    image: bsc_validator:latest
    environment:
     - AUTHORITY_NAME=charlie
    volumes:
      - ./keys/charlie:/data/keys
      - ./keys/password.txt:/data/keys/password.txt